### ISSUE TITLE
Add list of sample kfp pipelines for Tekton

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#118]
/kind feature

**Description:**
[A clear and concise description of what your proposal. What problem does it solve?]

Tracking issues for list of samples for kfp-tekton.
- [x] kubeflow-e2e #116 
- [x] flip-coin #117 
- [x] [Watson ML](https://github.com/kubeflow/pipelines/tree/master/samples/contrib/ibm-samples/watson)
- [x] [python to containerOp](https://github.com/kubeflow/pipelines/tree/master/samples/core/lightweight_component) #131 
- [x] [simpler katib example](https://github.com/kubeflow/pipelines/blob/master/components/kubeflow/katib-launcher/sample2.py) that can run on small machine #123 
- [x] Nested pipeline #145 
- [ ] custom on-prem pipeline with node selector and other pipelinerun features
- [ ] one gcp pipeline? since all the complex core examples are gcp only.
- [x] custom pipeline with ai ethics. #134 
- [ ] TFX using python to containerOp

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]
