### ISSUE TITLE
KFP-Tekton V2 tracker issue

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#1366]
/kind feature

**Description:**
- [ ] KFP-Tekton V2 code refactoring and optimization:
  - [ ] #1357 
  - [ ] #1361 
  - [ ] #1364

- [ ] KFP V2 upstream features:
  - [ ] KFP V1 feature complete:
    - [ ] Support all k8s spec on the new KFP V2 IR https://github.com/kubeflow/pipelines/issues/9768
    - [ ] Support log archive https://github.com/kubeflow/pipelines/issues/10036
    - [ ] Update our fluentd example to store the log archive file in the KFP V2 location (not implemented yet) #1563
  - [ ] KFP V2 Status-IR: KFP V2 tracking issue https://github.com/kubeflow/pipelines/issues/6110
    - [ ] https://github.com/kubeflow/pipelines/issues/8964
      - [ ] May need to implement the "Publisher" for updating dag and pipeline status according to original KFP V2 design [bit.ly/kfp-v2](https://bit.ly/kfp-v2).
    - [ ] https://github.com/kubeflow/pipelines/issues/8965
    - [ ] https://github.com/kubeflow/pipelines/issues/8966
  - [ ] Remove client dependency on schedule workflows and persistent agent 
    - [ ] https://github.com/kubeflow/pipelines/pull/6207
    - [ ] See can persistent agent be opted out or be crobjob for just asking api-server to sync the mlmd status to the kfp run status.

Once all these issues are resolved, we can push the Tekton compiler/executor spec code to upstream since it will only need to be embedded into the api-server.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]
