### ISSUE TITLE
Compiler issues reported by Watson

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/kfp-tekton#150]
/kind bug

Reported by Michalina  @udiknedormin

* identifiers are not checked for length, some of them fail on length check (63 characters is the limit)
* not all identifiers are escaping `_` signs (`_` -> `-`)
* no big data fix by default, instead it's hidden behind a flag, triggering very cryptic Tekton error
  * error message is "no such an output", which contradicts the definition
  * origins in Tekton-Pipelines way of handling outputs from termination-message
  * termination message has length cap, which can be easily exceeded for big inputs/outputs
  * Tekton-Pipelines doesn't do any error handling when parsing json from termination message, just parses empty list on error
  * messages that are too long don't seem to follow one pattern: they can have their end cut, their beginning cut or both
* big data fix still uses `results` to pass the whole value, not just the path, so the parsing error is still happening
* big data fix makes results multiplied: output A of step X is present in both X and `copy-artifacts` step injected by the compiler, Tekton takes both
* `copy-artifacts` only copies them out, for output artefacts, but doesn't copy them to the by-artifact inputs of consumers

**Comment by ckadner** [comment]
I think most of the reported problems should be related to these open issues:

- [ ] Validate identifiers #151
- [ ] Fix big data passing #63
- [ ] Verify generated Tekton YAML #137

**Comment by animeshsingh** [comment]
cc @fenglixa 

@ckadner can you connect with @fenglixa and split the effort?

**Comment by fenglixa** [comment]
I am tring to work on "Re-implement the fix_big_data_passing function" #63 firstly.

Also other issues inside need to be addressed: 

- [ ] Exit handler support #85
- [ ] messages that are too long don't seem to follow one pattern: they can have their end cut, their beginning cut or both
- [ ] Uses results to pass the whole value, not just the path, so the parsing error is still happening
- [ ] big data fix makes results multiplied: output A of step X is present in both X and copy-artifacts step injected by the compiler, Tekton takes both
- [ ] copy-artifacts only copies them out, for output artefacts, but doesn't copy them to the by-artifact inputs of consumers

**Comment by ckadner** [comment]
> I am trying to work on "Re-implement the fix_big_data_passing function" #63 firstly.

@fenglixa -- I assigned #63 to you. Thanks for your help!

**Comment by fenglixa** [comment]
Connected with @Udiknedormin on slack. This issue was addressed.  Seems it could be closed now.

/close
