### ISSUE TITLE
Compiler work items

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#18]
This is an **"umbrella issue"** to capture planned work items related to the `TektonCompiler`:

- [x] Generate a `Pipeline` with `Task`s instead of a `Task` with `steps` to allow parallel execution (PR #17) 
- [x] Allow passing output parameters as inputs for subsequent `Task`s (issue #19, PR #27)
- [x] Migrate to Tekton `0.11` to make use of API `v1beta1` (PR #27)
- [ ] Add Tekton integration tests (issue #28)
- [ ] Add support for `dsl.VolumeOp` (#51)
- [ ] Add support for `set_image_pull_secrets` (#54)
- [ ] Add support for `conditions` (#33)
- [x] Add support for _static_ `LoopArguments` (#67)
- [ ] Add support for _dynamic_ `LoopArguments` (#82)
- [x] Add support for `ParallelFor` (#67)
- [x] Option to generate Tekton `PipelineRun` spec (#62)
- [ ] Add support for Tekton `Workspace`s to share resources between `Task`s (#74)
- [x] Handler for checking Argo specific params, find equivalent for Tekton (#78 #80)
- [ ] Fix big data passing (#63)
- [ ] ...

### Specific template conversions:

Existing code that was copied from the KFP SDK compiler but temporarily commented out. See [`_op_to_template.py`](https://github.com/kubeflow/kfp-tekton/blob/ab5d433/sdk/python/kfp_tekton/compiler/_op_to_template.py#L51)):
- [ ] Add support for `dsl.ResourceOp` (#49)
- [ ] Add support for `artifacts` parameters (#64)
- [x] Add support for `affinity` (#65) (requires `PipelineRun` #62)
- [x] Add support for `initContainers` (#50)
- [x] Add support for metadata `pod_annotations` (#76)
- [x] Add support for metadata `pod_labels` (#76)
- [x] Add support for `node selector` (#65) (requires `PipelineRun` #62)
- [x] Add support for `retries` (#48)
- [x] Add support for `sidecars` (#42)
- [x] Add support for `timeout` (#46)
- [x] Add support for `tolerations` (#65) (requires `PipelineRun` #62)
- [x] Add support for `volumes` (#34)

In terms of prioritization, we could look at how often these features are used in any of the KFP pipeline examples (see [KFP samples test report](https://github.com/kubeflow/kfp-tekton/pull/32#issuecomment-601477548)). 

Of the `88` `dsl.pipeline` examples and samples found in the `kubeflow/pipelines` repository `54` fail:

```
  45 'volumes' are not (yet) implemented
  38 `dsl.ResourceOp` is not yet implemented
   4 `input artifacts` are not yet implemented
   3 'sidecars' are not (yet) implemented
   3 'retries' is not (yet) implemented
   1 'tolerations' is not (yet) implemented
   1 'timeout' is not (yet) implemented
   1 'nodeSelector' is not (yet) implemented
   1 'affinity' is not (yet) implemented
```

### Update on KFP testdata compilation failure reasons as of Apr 3, 2020:

```YAML
FAILURE: basic_no_decorator.py           - needs ExitHandlerOp, support pipeline with no decorator 
FAILURE: compose.py                      - needs function to flatten nested pipeline 
FAILURE: input_artifact_raw_value.py     - needs S3 compatible artifact passing
FAILURE: param_substitutions.py          - needs dsl.ResourceOp
FAILURE: resourceop_basic.py             - needs dsl.ResourceOp
FAILURE: volume_snapshotop_rokurl.py     - needs dsl.VolumeSnapshotOp
FAILURE: volume_snapshotop_sequential.py - needs dsl.VolumeSnapshotOp
FAILURE: volumeop_basic.py               - needs dsl.VolumeOp
FAILURE: volumeop_dag.py                 - needs dsl.VolumeOp
FAILURE: volumeop_parallel.py            - needs dsl.VolumeOp
FAILURE: volumeop_sequential.py          - needs dsl.VolumeOp
FAILURE: loop_over_lightweight_output.py - needs Tekton dynamic looping
FAILURE: withparam_global.py             - needs Tekton dynamic looping
FAILURE: withparam_global_dict.py        - needs Tekton dynamic looping
FAILURE: withparam_output.py             - needs Tekton dynamic looping
FAILURE: withparam_output_dict.py        - needs Tekton dynamic looping
```

### Mapping of features from Argo to Tekton:

General guidance to map KFP/Argo features to Tekton features can be found in the [KFP, Argo and Tekton Comparision Spreadsheet](https://docs.google.com/spreadsheets/d/1LFUy86MhVrU2cRhXNsDU-OBzB4BlkT9C0ASD3hoXqpo/edit#gid=979402121) maintained by @afrittoli

**Comment by ckadner** [comment]
@animeshsingh

**Comment by Tomcli** [comment]
Hi @ckadner, can you add the below tasks as well. There are more tasks in the spreadsheet, but i think we should prioritize the basic functionalities before dive in deeper to the harder ones.

- Add support for `dsl.VolumeOp`
- Handler for checking Argo specific params
- Add support for `set_image_pull_secrets`
- Add support for passing artifacts.

**Comment by Tomcli** [comment]
Also I think we need a way to itemize each of these tasks into individual issues so that people can claim and start working on it.

**Comment by ckadner** [comment]
@animeshsingh -- @Tomcli provided an update on the 16 remaining KFP `testdata` compilation failures along with their respective main causes of failure (Apr 2, 2020):

```YAML
FAILURE: basic_no_decorator.py           - needs ExitHandlerOp, support pipeline with no decorator 
FAILURE: compose.py                      - needs function to flatten nested pipeline 
FAILURE: input_artifact_raw_value.py     - needs S3 compatible artifact passing
FAILURE: param_substitutions.py          - needs dsl.ResourceOp
FAILURE: resourceop_basic.py             - needs dsl.ResourceOp
FAILURE: volume_snapshotop_rokurl.py     - needs dsl.VolumeSnapshotOp
FAILURE: volume_snapshotop_sequential.py - needs dsl.VolumeSnapshotOp
FAILURE: volumeop_basic.py               - needs dsl.VolumeOp
FAILURE: volumeop_dag.py                 - needs dsl.VolumeOp
FAILURE: volumeop_parallel.py            - needs dsl.VolumeOp
FAILURE: volumeop_sequential.py          - needs dsl.VolumeOp
FAILURE: loop_over_lightweight_output.py - needs Tekton dynamic looping
FAILURE: withparam_global.py             - needs Tekton dynamic looping
FAILURE: withparam_global_dict.py        - needs Tekton dynamic looping
FAILURE: withparam_output.py             - needs Tekton dynamic looping
FAILURE: withparam_output_dict.py        - needs Tekton dynamic looping
```
Thanks @Tomcli for analyzing those!

**Comment by ckadner** [comment]
@animeshsingh -- I made a few temporary code changes so the compiler won't exit after the first exception but instead to log error messages. This should allow to capture all the known missing features which a pipeline is utilizing, instead of only reporting the first failure per pipeline.

Then I ran the compile report script over 3 sets of pipelines:
1. KFP compiler `testdata` (the usual 30 pipelines)
2. KFP `core` samples (some of those are duplicated in `testdata`)
3. 3rd-party contributed pipelines (`*/contrib/*`)

Here are the respective outputs:

**Note 1**: the totals do not add up to the sum of all errors, since each pipeline can "throw" multiple or no errors.

**Note 2**: `dsl.VolumeOp` and `dsl.VolumeSnapshotOp` and more inherit from `dsl.ResourceOp`. I have split those out separately here. 

### 1. Pipelines from KFP compiler `testdata` folder:

```YAML
SUCCESS: sdk/python/tests/compiler/testdata/add_pod_env.py
SUCCESS: sdk/python/tests/compiler/testdata/artifact_location.py
SUCCESS: sdk/python/tests/compiler/testdata/basic.py
FAILURE: sdk/python/tests/compiler/testdata/basic_no_decorator.py
SUCCESS: sdk/python/tests/compiler/testdata/coin.py
FAILURE: sdk/python/tests/compiler/testdata/compose.py
SUCCESS: sdk/python/tests/compiler/testdata/default_value.py
FAILURE: sdk/python/tests/compiler/testdata/input_artifact_raw_value.py
FAILURE: sdk/python/tests/compiler/testdata/loop_over_lightweight_output.py
SUCCESS: sdk/python/tests/compiler/testdata/param_op_transform.py
FAILURE: sdk/python/tests/compiler/testdata/param_substitutions.py
SUCCESS: sdk/python/tests/compiler/testdata/pipelineparams.py
SUCCESS: sdk/python/tests/compiler/testdata/recursive_do_while.py
SUCCESS: sdk/python/tests/compiler/testdata/recursive_while.py
FAILURE: sdk/python/tests/compiler/testdata/resourceop_basic.py
SUCCESS: sdk/python/tests/compiler/testdata/sidecar.py
SUCCESS: sdk/python/tests/compiler/testdata/timeout.py
SUCCESS: sdk/python/tests/compiler/testdata/volume.py
FAILURE: sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.py
FAILURE: sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.py
FAILURE: sdk/python/tests/compiler/testdata/volumeop_basic.py
FAILURE: sdk/python/tests/compiler/testdata/volumeop_dag.py
FAILURE: sdk/python/tests/compiler/testdata/volumeop_parallel.py
FAILURE: sdk/python/tests/compiler/testdata/volumeop_sequential.py
SUCCESS: sdk/python/tests/compiler/testdata/withitem_basic.py
SUCCESS: sdk/python/tests/compiler/testdata/withitem_nested.py
FAILURE: sdk/python/tests/compiler/testdata/withparam_global.py
FAILURE: sdk/python/tests/compiler/testdata/withparam_global_dict.py
FAILURE: sdk/python/tests/compiler/testdata/withparam_output.py
FAILURE: sdk/python/tests/compiler/testdata/withparam_output_dict.py

Success: 14
Failure: 16
Total:   30

Occurences of NotImplementedError:
   9 dsl.VolumeOp is not yet implemented (dsl.ResourceOp)
   5 dsl.VolumeSnapshotOp is not yet implemented (dsl.ResourceOp)
   5 dynamic params are not yet implemented
   4 input artifacts are not yet implemented
   1 dsl.ResourceOp is not yet implemented

Occurences of other Errors:
   1 ValueError: There are multiple pipelines: ['save_most_frequent_word', 'download_save_most_frequent_word']. Please specify --function.
   1 ValueError: A function with @dsl.pipeline decorator is required in the py file.
```
---
### 2. KFP core samples:

```YAML
SUCCESS: samples/core/helloworld/hello_world.py
SUCCESS: samples/core/execution_order/execution_order.py
FAILURE: samples/core/volume_ops/volume_ops.py
SUCCESS: samples/core/preemptible_tpu_gpu/preemptible_tpu_gpu.py
SUCCESS: samples/core/retry/retry.py
SUCCESS: samples/core/recursion/recursion.py
FAILURE: samples/core/volume_snapshot_ops/volume_snapshot_ops.py
FAILURE: samples/core/xgboost_training_cm/xgboost_training_cm.py
FAILURE: samples/core/loop_output/loop_output.py
SUCCESS: samples/core/sequential/sequential.py
SUCCESS: samples/core/exit_handler/exit_handler.py
SUCCESS: samples/core/imagepullsecrets/imagepullsecrets.py
SUCCESS: samples/core/parallel_join/parallel_join.py
SUCCESS: samples/core/loop_static/loop_static.py
SUCCESS: samples/core/condition/condition.py
SUCCESS: samples/core/pipeline_transformers/pipeline_transformers.py
FAILURE: samples/core/loop_parameter/loop_parameter.py
FAILURE: samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
SUCCESS: samples/core/artifact_location/artifact_location.py
SUCCESS: samples/core/sidecar/sidecar.py
SUCCESS: samples/core/secret/secret.py
FAILURE: samples/core/resource_ops/resource_ops.py
FAILURE: samples/tutorials/DSL - Control structures/DSL - Control structures.py
SUCCESS: components/kubeflow/launcher/sample.py
FAILURE: components/kubeflow/katib-launcher/sample.py
FAILURE: components/kubeflow/katib-launcher/sample2.py

Success: 16
Failure: 10
Total:   26

Occurences of NotImplementedError:
   3 dsl.VolumeSnapshotOp is not yet implemented
   2 dsl.VolumeOp is not yet implemented
   2 dynamic params are not yet implemented
   1 dsl.ResourceOp is not yet implemented

Occurences of other Errors:
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.uid}}, {{pod.name}}
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{.Trial}}, {{.NameSpace}}, {{.Name}}, {{.Value}}
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{.Name}}, {{.Value}}, {{.Trial}}, {{.NameSpace}}
   1 ValueError: There are multiple pipelines: ['flipcoin_pipeline', 'flipcoin_exit_pipeline']. Please specify --function.
   1 ValueError: A function with @dsl.pipeline decorator is required in the py file.
```
---
### 3. pipelines contributed by 3rd parties:

```YAML
SUCCESS: contrib/samples/openvino/deployer/deployer.py
SUCCESS: contrib/samples/openvino/model_optimizer/convert_model_pipeline.py
SUCCESS: contrib/samples/openvino/tf-slim/tf-slim.py
SUCCESS: contrib/samples/openvino/predict/numpy_predict.py
FAILURE: samples/contrib/volume_ops/volumeop_dag.py
FAILURE: samples/contrib/volume_ops/volumeop_parallel.py
FAILURE: samples/contrib/volume_ops/volumeop_sequential.py
SUCCESS: samples/contrib/ibm-samples/ffdl-seldon/ffdl_pipeline.py
SUCCESS: samples/contrib/ibm-samples/watson/watson_train_serve_pipeline.py
SUCCESS: samples/contrib/ibm-samples/openscale/openscale.py
FAILURE: samples/contrib/azure-samples/databricks-pipelines/databricks_notebook_pipeline.py
FAILURE: samples/contrib/azure-samples/databricks-pipelines/databricks_run_pipeline.py
FAILURE: samples/contrib/azure-samples/databricks-pipelines/databricks_cluster_pipeline.py
FAILURE: samples/contrib/azure-samples/databricks-pipelines/databricks_secretscope_pipeline.py
FAILURE: samples/contrib/azure-samples/databricks-pipelines/databricks_workspaceitem_pipeline.py
FAILURE: samples/contrib/azure-samples/databricks-pipelines/databricks_job_pipeline.py
FAILURE: samples/contrib/volume_snapshot_ops/volume_snapshotop_rokurl.py
FAILURE: samples/contrib/nvidia-resnet/pipeline/src/pipeline.py
FAILURE: samples/contrib/seldon/mnist_tf.py
FAILURE: samples/contrib/seldon/iris_storagebucket.py
FAILURE: samples/contrib/seldon/mabdeploy_seldon.py
FAILURE: samples/contrib/seldon/mnist_tf_volume.py
SUCCESS: samples/contrib/aws-samples/ground_truth_pipeline_demo/mini-image-classification-pipeline.py
SUCCESS: samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py
SUCCESS: samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
SUCCESS: samples/contrib/aws-samples/titanic-survival-prediction/titanic-survival-prediction.py
FAILURE: samples/contrib/arena-samples/mpi/mpi_run.py
FAILURE: samples/contrib/arena-samples/standalonejob/standalone_pipeline.py

Success: 11
Failure: 17
Total:   28

Occurences of NotImplementedError:
   9 dsl.VolumeOp is not yet implemented (dsl.ResourceOp)
   6 dsl.ResourceOp is not yet implemented (dsl.ResourceOp)
   4 dsl.SubmitRunOp is not yet implemented (dsl.ResourceOp)
   4 dsl.DeleteRunOp is not yet implemented (dsl.ResourceOp)
   2 dsl.VolumeSnapshotOp is not yet implemented (dsl.ResourceOp)
   2 dsl.ImportWorkspaceItemOp is not yet implemented (dsl.ResourceOp)
   2 dsl.DeleteWorkspaceItemOp is not yet implemented (dsl.ResourceOp)
   2 dsl.DeleteSecretScopeOp is not yet implemented (dsl.ResourceOp)
   2 dsl.DeleteJobOp is not yet implemented (dsl.ResourceOp)
   2 dsl.DeleteClusterOp is not yet implemented (dsl.ResourceOp)
   2 dsl.CreateSecretScopeOp is not yet implemented (dsl.ResourceOp)
   2 dsl.CreateJobOp is not yet implemented (dsl.ResourceOp)
   2 dsl.CreateClusterOp is not yet implemented (dsl.ResourceOp)
   1 dsl.DeleteDbfsBlockOp is not yet implemented (dsl.ResourceOp)
   1 dsl.CreateDbfsBlockOp is not yet implemented

Occurences of other Errors:
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.name}}
   1 AttributeError: module 'arena' has no attribute 'standalone_job_op'
   1 AttributeError: module 'arena' has no attribute 'mpi_job_op'
```

**Comment by animeshsingh** [comment]
Thanks @ckadner.  Summarizing the information above

Averaging out currently, **we have 41/84 successful - so ~50%** 

Occurences of NotImplementedError:
   20 dsl.VolumeOp is not yet implemented (dsl.ResourceOp)
   10 dsl.VolumeSnapshotOp is not yet implemented (dsl.ResourceOp)
   8 dsl.ResourceOp is not yet implemented
   7 dynamic params are not yet implemented
   4 input artifacts are not yet implemented

Occurences of other Errors:
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.uid}}, {{pod.name}}
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{.Trial}}, {{.NameSpace}}, {{.Name}}, {{.Value}}

cc @Tomcli @fenglixa @vincent-pli

**Comment by ckadner** [comment]
@animeshsingh -- This is an update of compilation success/failure and failure reasons for KFP testdata and samples (4/14, incl. PR #92):

49/84 successful - so ~58% (increase of 8 more successful)

---
### 1. KFP `testdata` scripts

```YAML
SUCCESS: sdk/python/tests/compiler/testdata/add_pod_env.py
SUCCESS: sdk/python/tests/compiler/testdata/artifact_location.py
SUCCESS: sdk/python/tests/compiler/testdata/basic.py
FAILURE: sdk/python/tests/compiler/testdata/basic_no_decorator.py
FAILURE: sdk/python/tests/compiler/testdata/coin.py
FAILURE: sdk/python/tests/compiler/testdata/compose.py
SUCCESS: sdk/python/tests/compiler/testdata/default_value.py
FAILURE: sdk/python/tests/compiler/testdata/input_artifact_raw_value.py
FAILURE: sdk/python/tests/compiler/testdata/loop_over_lightweight_output.py
SUCCESS: sdk/python/tests/compiler/testdata/param_op_transform.py
FAILURE: sdk/python/tests/compiler/testdata/param_substitutions.py
SUCCESS: sdk/python/tests/compiler/testdata/pipelineparams.py
FAILURE: sdk/python/tests/compiler/testdata/recursive_do_while.py
SUCCESS: sdk/python/tests/compiler/testdata/recursive_while.py
SUCCESS: sdk/python/tests/compiler/testdata/resourceop_basic.py
SUCCESS: sdk/python/tests/compiler/testdata/sidecar.py
SUCCESS: sdk/python/tests/compiler/testdata/timeout.py
SUCCESS: sdk/python/tests/compiler/testdata/volume.py
FAILURE: sdk/python/tests/compiler/testdata/volume_snapshotop_rokurl.py
FAILURE: sdk/python/tests/compiler/testdata/volume_snapshotop_sequential.py
FAILURE: sdk/python/tests/compiler/testdata/volumeop_basic.py
FAILURE: sdk/python/tests/compiler/testdata/volumeop_dag.py
FAILURE: sdk/python/tests/compiler/testdata/volumeop_parallel.py
FAILURE: sdk/python/tests/compiler/testdata/volumeop_sequential.py
SUCCESS: sdk/python/tests/compiler/testdata/withitem_basic.py
SUCCESS: sdk/python/tests/compiler/testdata/withitem_nested.py
FAILURE: sdk/python/tests/compiler/testdata/withparam_global.py
FAILURE: sdk/python/tests/compiler/testdata/withparam_global_dict.py
FAILURE: sdk/python/tests/compiler/testdata/withparam_output.py
FAILURE: sdk/python/tests/compiler/testdata/withparam_output_dict.py

Success: 13
Failure: 17
Total:   30

Occurences of NotImplementedError:
   5 dynamic params are not yet implemented
   4 input artifacts are not yet implemented

Occurences of other Errors:
   7 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.name}}
   2 TypeError: Conditions do not currently support parameter passing from task outputs
   1 ValueError: There are multiple pipelines: ['save_most_frequent_word', 'download_save_most_frequent_word']. Please specify --function.
   1 ValueError: A function with @dsl.pipeline decorator is required in the py file.
```

---
### 2. KFP `core` samples

```YAML
SUCCESS: samples/core/helloworld/hello_world.py
SUCCESS: samples/core/execution_order/execution_order.py
FAILURE: samples/core/volume_ops/volume_ops.py
SUCCESS: samples/core/preemptible_tpu_gpu/preemptible_tpu_gpu.py
SUCCESS: samples/core/retry/retry.py
FAILURE: samples/core/recursion/recursion.py
FAILURE: samples/core/volume_snapshot_ops/volume_snapshot_ops.py
FAILURE: samples/core/xgboost_training_cm/xgboost_training_cm.py
FAILURE: samples/core/loop_output/loop_output.py
SUCCESS: samples/core/sequential/sequential.py
SUCCESS: samples/core/exit_handler/exit_handler.py
SUCCESS: samples/core/imagepullsecrets/imagepullsecrets.py
SUCCESS: samples/core/parallel_join/parallel_join.py
SUCCESS: samples/core/loop_static/loop_static.py
FAILURE: samples/core/condition/condition.py
SUCCESS: samples/core/pipeline_transformers/pipeline_transformers.py
FAILURE: samples/core/loop_parameter/loop_parameter.py
FAILURE: samples/core/parameterized_tfx_oss/parameterized_tfx_oss.py
SUCCESS: samples/core/artifact_location/artifact_location.py
SUCCESS: samples/core/sidecar/sidecar.py
SUCCESS: samples/core/secret/secret.py
SUCCESS: samples/core/resource_ops/resource_ops.py
FAILURE: samples/tutorials/DSL - Control structures/DSL - Control structures.py
SUCCESS: components/kubeflow/launcher/sample.py
SUCCESS: components/kubeflow/katib-launcher/sample.py
SUCCESS: components/kubeflow/katib-launcher/sample2.py

Success: 17
Failure: 9
Total:   26

Occurences of NotImplementedError:
   2 dynamic params are not yet implemented

Occurences of other Errors:
   3 TypeError: Conditions do not currently support parameter passing from task outputs
   2 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.name}}
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.uid}}, {{pod.name}}
   1 ValueError: There are multiple pipelines: ['flipcoin_pipeline', 'flipcoin_exit_pipeline']. Please specify --function.
   1 ValueError: A function with @dsl.pipeline decorator is required in the py file.
```

---
### 3. 3rd-party contributed samples

```YAML
SUCCESS: contrib/samples/openvino/deployer/deployer.py
SUCCESS: contrib/samples/openvino/model_optimizer/convert_model_pipeline.py
SUCCESS: contrib/samples/openvino/tf-slim/tf-slim.py
SUCCESS: contrib/samples/openvino/predict/numpy_predict.py
FAILURE: samples/contrib/volume_ops/volumeop_dag.py
FAILURE: samples/contrib/volume_ops/volumeop_parallel.py
FAILURE: samples/contrib/volume_ops/volumeop_sequential.py
SUCCESS: samples/contrib/ibm-samples/ffdl-seldon/ffdl_pipeline.py
SUCCESS: samples/contrib/ibm-samples/watson/watson_train_serve_pipeline.py
SUCCESS: samples/contrib/ibm-samples/openscale/openscale.py
SUCCESS: samples/contrib/azure-samples/databricks-pipelines/databricks_notebook_pipeline.py
SUCCESS: samples/contrib/azure-samples/databricks-pipelines/databricks_run_pipeline.py
SUCCESS: samples/contrib/azure-samples/databricks-pipelines/databricks_cluster_pipeline.py
SUCCESS: samples/contrib/azure-samples/databricks-pipelines/databricks_secretscope_pipeline.py
SUCCESS: samples/contrib/azure-samples/databricks-pipelines/databricks_workspaceitem_pipeline.py
SUCCESS: samples/contrib/azure-samples/databricks-pipelines/databricks_job_pipeline.py
FAILURE: samples/contrib/volume_snapshot_ops/volume_snapshotop_rokurl.py
FAILURE: samples/contrib/nvidia-resnet/pipeline/src/pipeline.py
FAILURE: samples/contrib/seldon/mnist_tf.py
SUCCESS: samples/contrib/seldon/iris_storagebucket.py
SUCCESS: samples/contrib/seldon/mabdeploy_seldon.py
FAILURE: samples/contrib/seldon/mnist_tf_volume.py
SUCCESS: samples/contrib/aws-samples/ground_truth_pipeline_demo/mini-image-classification-pipeline.py
SUCCESS: samples/contrib/aws-samples/mnist-kmeans-sagemaker/kmeans-hpo-pipeline.py
SUCCESS: samples/contrib/aws-samples/mnist-kmeans-sagemaker/mnist-classification-pipeline.py
SUCCESS: samples/contrib/aws-samples/titanic-survival-prediction/titanic-survival-prediction.py
FAILURE: samples/contrib/arena-samples/mpi/mpi_run.py
FAILURE: samples/contrib/arena-samples/standalonejob/standalone_pipeline.py

Success: 19
Failure: 9
Total:   28

Occurences of NotImplementedError:

Occurences of other Errors:
   5 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.name}}
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.uid}}, {{workflow.name}}
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.name}}, {{workflow.uid}}
   1 AttributeError: module 'arena' has no attribute 'standalone_job_op'
   1 AttributeError: module 'arena' has no attribute 'mpi_job_op'
```

**Comment by ckadner** [comment]
@animeshsingh 

Update of the compilation success/failure status as of EOD 4/22:

### 1. KFP compiler testdata (the usual 30 pipelines)
	Success: 25
	Failure: 5
	Total:   30

### 2. KFP core samples
	Success: 21
	Failure: 5
	Total:   26

### 3. Pipeline samples contributed by 3rd-parties (*/contrib/*)
	Success: 23
	Failure: 5
	Total:   28


**Overall success rate: 69/84 = 82%**

**Occurences of NotImplementedError:**
   7 dynamic params are not yet implemented

**Occurences of other Errors:**
   3 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.uid}}
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{workflow.name}}
   1 ValueError: These Argo variables are not supported in Tekton Pipeline: {{pod.name}}
