### ISSUE TITLE
TODO list for next release

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#326]
/kind feature

**Description:**
- [ ] enhance deployment method
- [ ] enhance the test suite
- [ ] generate an updated report for the supported dsl features
- [ ] get the openscale pipeline fixed
- [ ] Investigate KFP 1.1 rebasing.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]
