### ISSUE TITLE
issue tracker: loop feature support

### ISSUE THREAD

**Issue by Tomcli** [kubeflow/kfp-tekton#443]
/kind feature

**Description:**
- [x] #413 update compiler to produce new loop crd
- [x] #416 https://github.com/tektoncd/pipeline/issues/3682 find ways to put the loop crd spec into the pipelinerun crd
- [x] #431 add ui support for new loop syntax
- [x] Tekton 0.21 release for taking task results as parameters.

**Additional information:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by fenglixa** [comment]
Thanks @Tomcli , 

Another Loop Task for community:  Support parallelism parameter as below:

`dsl.ParallelFor(produce_numbers_task.output, parallelism=4)`

**Comment by Tomcli** [comment]
done
/close
