### ISSUE TITLE
Should the compiler generate Pipeline or PipelineRun

### ISSUE THREAD

**Issue by ckadner** [kubeflow/kfp-tekton#59]
This is a general discussion, not a work item.

Conceptually a `Pipeline` is a static specification orchestrating how a set of `Task`s should be executed. A `PipelineRun` is an instantiation of a pipeline. A pipeline is a re-usable artifact that can be "run" repeatedly, a pipeline-run is one-and-done.

Currently the KFP-Tekton compiler generates a YAML with (multiple) `Tasks`(s) and one `Pipeline` document. There are however certain features supported by the KFP DSL which are not easily transferred into an equivalent feature in Tekton `Pipelines`, but instead require the concept of a `PipelineRun`, like mounting PVC volume to a pipeline workspace or setting a timeout at the pipeline level.

### Linked issues

- [x] Pipeline level timeout #56 
- [x] Passing parameters between tasks [#41](https://github.com/kubeflow/kfp-tekton/issues/41#issuecomment-603452575)
- [x] Volume mounts #51
- [ ] Generate PipelineRun with embedded `pipelineSpec` and `taskSpec` #143

**Comment by Tomcli** [comment]
For comparison, every workflow in Argo is like a PipelineRun. Therefore, when we upload a pipeline in kfp, it's treated as a template and stored in object storage instead of applying the template to Kubernetes.

**Comment by ckadner** [comment]
> For comparison, every workflow in Argo is like a PipelineRun. Therefore, when we upload a pipeline in kfp, it's treated as a template and stored in object storage instead of applying the template to Kubernetes.

True. But for Kubeflow Pipelines with Argo there is the KFP UI which allows users to interact with pipelines and provide parameters and see logs, etc. For Tekton we have to rely on `kubectl` and `tkn`. If we generate `PipelineRun`s then a user cannot provide parameters at run-time, rather parameters, volume mounts, PVC are locked in at compilation time.

**Comment by ckadner** [comment]
@afrittoli @animeshsingh @fenglixa @vincent-pli

**Comment by Tomcli** [comment]
https://github.com/tektoncd/cli/issues/786

**Comment by ckadner** [comment]
we could also introduce a `--generate-pipelinerun` flag for the `dsl-compile-tekton` CLI

**Comment by Tomcli** [comment]
I will add a flag for development purpose and we should push the cli team to support workspaces.

**Comment by fenglixa** [comment]
Great, I think we should support generate-pipelinerun feature, it's convenient for user to run the whole workflow directly, but not just leave several templates there, also, [pipelinerun](https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md) has several fields which could be defined in there, including pipeline timeout.

**Comment by Tomcli** [comment]
generating pipelinerun might also be useful for adding pod-template such as node selector and affinity features  https://github.com/tektoncd/pipeline/blob/master/docs/pipelineruns.md#pod-template

**Comment by fenglixa** [comment]
Personally, I think we should generate tekton pipelinerun by default to align with argo workflow but not pipeline. 
We may need to list pros and cons for each optionals and adopt one of them, convenient for further API and UI integration

**Comment by animeshsingh** [comment]
Given more preference towards pipelinerun, lets go with that

**Comment by vincent-pli** [comment]
`Pipelinerun` with `Pipeline` definition embed:
```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-with-taskspec-to-echo-good-morning
spec:
  pipelineSpec:
    tasks:
      - name: echo-good-morning
        taskSpec:
          steps:
            - name: echo
              image: ubuntu
              script: |
                #!/usr/bin/env bash
                echo "Good Morning!"
```

**Comment by ckadner** [comment]
> `PipelineRun` with `Pipeline` definition embed

I think  @Tomcli 's approach (PR #62) with generating an optional `PipelineRun` in addition to the existing `Pipeline` with `Tasks` will be the best compromise and allows to keep existing code intact. At least for the time being.

**Comment by afrittoli** [comment]
> > `PipelineRun` with `Pipeline` definition embed
> 
> I think @Tomcli 's approach (PR #62) with generating an optional `PipelineRun` in addition to the existing `Pipeline` with `Tasks` will be the best compromise and allows to keep existing code intact. At least for the time being.

Eventually you could have a flag that let you decide whether to embed the pipeline in the pipelinerun or not.

**Comment by afrittoli** [comment]
Whether you want to use Pipeline or PipelineRun depends on what kind of experience you want to give to end-users.

Tekton separates static definitions from runtimes and it provides a component called “triggers” that allow you to create runtime objects with several presets. Today “triggers” only respond to HTTPs requests, but I can imagine a future were it will be possible to run “triggers” in different ways.
It seems to be that that separation between static definition and runtime is not so clear in the python sdk, so after reading all the discussion it feels like you may have to go with generating PipelineRuns. If you still need to support changing some of the parameters at run time, you could support that using kustomize overlay.

**Comment by ckadner** [comment]
https://github.com/tektoncd/pipeline/issues/2767

**Comment by ckadner** [comment]
**Related issues:**
- Generate `PipelineRun` with embedded `pipelineSpec` and `taskSpec` #143 #166
- Unsupported features for embedded pipelineSpec, taskSpec? [tektoncd/pipeline #2767](https://github.com/tektoncd/pipeline/issues/2767)

**Comment by Udiknedormin** [comment]
Shouldn't this be closed, considering [issue #143](https://github.com/kubeflow/kfp-tekton/issues/143) has been closed with [PR #166](https://github.com/kubeflow/kfp-tekton/pull/166)?

**Comment by Tomcli** [comment]
Thanks @Udiknedormin 
/close
